feat: Trips são filtradas a partir do Service ID
RJ-SMTR/mobilidade-rio-app pull request #78
Opened 2023-03-08 20:25 UTC by Gabriel0109

### Mudanças
- Trips são filtradas a partir do service_id, fazendo a checagem se o dia está presente em calendar_dates, se não está a pesquisa se baseia no dia da semana e checa em calendar o service_id
- A filtragem considera o trip_short_name e assim separa o array de form crescente, se tiver letras ele desconsidera na checagem e tem como base só o numero na frente dele 
- Texto do header para ficar igual a da home

2023-03-08 21:03 UTC, fernandascovino commented on src/components/Header/Header.jsx
> +                        <h1 className={`text-lg text-center + ${styles.headerText}`}>Saiba quais linhas de ônibus passam nos pontos da cidade</h1>
```suggestion
                        <h1 className={`text-lg text-center + ${styles.headerText}`}>Saiba quais linhas passam nos pontos da cidade</h1>
```

só tirar o onibus por conta do BRT, @Gabriel0109 vale mudar tbm na home

2023-03-08 21:09 UTC, fernandascovino commented on src/hooks/getRoutes.jsx
> +    function compareTripName(a, b) {
o que é `a` e `b` aqui?

a regra mais especifica seria:
1. se não é LECD:
- remove as letras
- ordena pelo numero
2. se é LECD, lista por ultimo

2023-03-08 21:11 UTC, fernandascovino requested changes
deixei alguns comentarios p alteracao

2023-03-08 21:17 UTC, Gabriel0109 commented on src/hooks/getRoutes.jsx
> +    function compareTripName(a, b) {
A e B são os itens de comparação, nesse caso o trip_short_name, então ele pega por exemplo: a = 52 e b = 51, como o item A é maior que o item B,ele coloca o índice do item A um a mais que o item B e assim por diante com todos os itens q tiver no array

2023-03-08 22:18 UTC, fernandascovino commented on src/hooks/getRoutes.jsx
> +    function compareTripName(a, b) {
Hnm entendi. Os tipos de trip_short_name que temos hj sao:

- XX (BRT)
- XXX (SPPO regular)
- SYXXX (SPPO variante - Noturno, Variante, Parcial, etc)
- LECDXX (SPPO linhas experimentais)

2023-03-09 14:41 UTC, fernandascovino commented on src/components/Header/Header.jsx
> +                        <h1 className={`text-lg text-center + ${styles.headerText}`}>Saiba quais linhas passam nos pontos da cidade</h1>
```suggestion
                        <h1 className={`text-lg text-center + ${styles.headerText}`}>Saiba quais linhas passam na cidade</h1>
```

2023-03-09 14:42 UTC, fernandascovino commented on src/pages/SearchMain.jsx
> +                    Saiba quais linhas passam nos pontos da cidade
```suggestion
                    Saiba quais linhas passam na cidade
```

2023-03-09 14:42 UTC, fernandascovino approved these changes
lgtm o/

2023-03-09 14:43 UTC, merged